import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { Open_Sans } from "next/font/google";
import Modals from "@/components/provider/Modals";
import Provider from "@/components/Provider";
import SignIn from "@/components/modals/SignIn";

const font = Open_Sans({ subsets: ["latin"] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Taskify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        <Provider>
          <Modals />
          <Navbar />
          <div className="h-full max-w-[2520px] mx-auto pt-20 px-2 sm:px-3 md:px-4 ">
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
